### PR TITLE
Remove console.log

### PR DESCRIPTION
**Pull request by visadb**
The console.log prints unnecessary stuff to the console.

### CODE REVIEW

**Comment by visadb** [comment]
Thanks for merging. It would be nice if you could release a new version with this change.

**Comment by nsams** [comment]
done...

**Comment by visadb** [comment]
Great! One more thing: could also update the version in package.json and publish to npm, so that we could take the new version in use.

Btw, thanks for this module, it helps us a lot.

**Comment by nsams** [comment]
done :D

**Pull request merged**
